### ISSUE TITLE
Can't select players on /matchresult.html when holding mouse button down

### ISSUE THREAD

**Issue by czarnecki** [adessoAG/adessoKicker#213] opened 2019-03-13 12:25 UTC
When showing the site to others they tried so select users by clicking on their names in the dropdown but were confused when this wouldn't select the user.
The user can only be selected by clicking on the whitespace behind their name.

**Comment by JanSchneider1** [comment] 2019-03-13 12:47
Which version were you showing? I tried the current version of the master and I can't reproduce this issue.

**Comment by JanSchneider1** [comment] 2019-03-13 12:50
Do you maybe mean a different issue. I understand the problem as follows, when a person tries to select a searched user in the search bar and clicks on it, it wouldn't select him except when he clicks on the white background like the user name is blocking the click

**Comment by JanSchneider1** [comment] 2019-03-13 12:52
Also something interesting to know for me would be if something happened instead if they click on user, like closing the search bar as I fixed an issue jsut now related to this

**Comment by czarnecki** [comment] 2019-03-13 12:52
Tried it myself now and it's a bit unreliable. Sometimes if you click between the first and last name the click won't register

**Comment by czarnecki** [comment] 2019-03-13 12:59
Checked out your `fixing-searchbar` Branch and I can't reproduce it anymore. Seems to be fixed.

**Comment by JanSchneider1** [comment] 2019-03-13 13:34
I was able to reproduce this bug! 
But the conditions were different as you testers described. 
The reason why you can't select a user has **nothing to do with where your cursor is when clicking**. 
The clicking is programmend in a way that after a certain amount of time the menu closes when the input field loses focus. 
So when you click on a user an hold it the button the onClick won't trigger and the menu closes after the few miliseconds passed and you're left without selecting a user. I'm going to change the onClick so it triggers so that you select a user when the mouse button goes down

**Comment by JanSchneider1** [comment] 2019-03-13 14:47
Yes, I solved it now and I came across a good solution. As the **mousedown** event fires before the on blur and focus event, I can use **preventDefault** on the list elements causing the searchbar not to lose focus. Additionaly we don't need that weird workraound were I had to set a delay so the searchbar closes after a certain amount of time

**Closed by JanSchneider1** 2019-03-13 14:47 UTC
